"""Typed surface of the compiled mantis._engine extension (crates/mantis-bridge).

The ONE stub: maturin installs it beside the module and pyright reads it through `stubPath`.
>300 justify (R8): a 1:1 typed mirror of the compiled mantis._engine surface — its length is the bridge API's, and a module stub cannot be split.
Checked against the runtime surface in both directions by
tests/bridge/test_engine_stub_matches_runtime.py. Numpy arrays are typed as
`numpy.ndarray` (dtype/shape documented in docstrings on the Rust side).
"""

from typing import Any

import numpy

# --------------------------------------------------------------------------- #
# Exceptions
# --------------------------------------------------------------------------- #
class WireAlreadyConsumed(Exception):
    """Raised when GraphWire.take() is called a second time (single-read latch)."""

class RunnerDrainPoisoned(RuntimeError):
    """Raised when a runner drain queue's lock is poisoned: a worker panicked mid-write."""

class SelectionDesync(RuntimeError):
    """Raised when the PUCT descent selects a child whose `action_idx` decodes to a cell the
    board refuses — the tree and the board have desynchronised (AUDIT-1 F-02).

    This replaces a `pyo3_runtime.PanicException` that `selfplay/worker.py` used to recover
    from by matching the panic's own message text.
    """

# --------------------------------------------------------------------------- #
# Board (unsendable — single-thread Python ownership)
# --------------------------------------------------------------------------- #
class Board:
    def __init__(self) -> None: ...
    @staticmethod
    def with_encoding_name(name: str) -> Board: ...
    def apply_move(self, q: int, r: int) -> None: ...
    def check_win(self) -> bool: ...
    def winner(self) -> int | None: ...
    def find_winning_line(self) -> list[tuple[int, int]]: ...
    def count_winning_moves(self, player: int) -> int: ...
    def winning_moves(self, player: int) -> list[tuple[int, int]]: ...
    def first_winning_move(self, player: int) -> tuple[int, int] | None: ...
    def has_player_long_run(self, player: int, min_len: int) -> bool: ...
    def forced_win_move(self, depth: int) -> tuple[int, int] | None: ...
    def legal_moves(self) -> list[tuple[int, int]]: ...
    def legal_move_count(self) -> int: ...
    def is_legal(self, q: int, r: int) -> bool: ...
    def get(self, q: int, r: int) -> int: ...
    @property
    def current_player(self) -> int: ...
    @property
    def moves_remaining(self) -> int: ...
    @property
    def ply(self) -> int: ...
    def legal_move_radius(self) -> int: ...
    def zobrist_hash(self) -> int: ...
    def to_flat(self, q: int, r: int) -> int: ...
    @property
    def size(self) -> int: ...
    def get_stones(self) -> list[tuple[int, int, int]]: ...
    def clone(self) -> Board: ...
    def __copy__(self) -> Board: ...
    def __deepcopy__(self, memo: Any) -> Board: ...
    def __repr__(self) -> str: ...

# --------------------------------------------------------------------------- #
# RegistrySpec (encoding schema view over &'static RegistrySpec)
# --------------------------------------------------------------------------- #
class RegistrySpec:
    @property
    def name(self) -> str: ...
    @property
    def board_size(self) -> int: ...
    @property
    def trunk_size(self) -> int: ...
    @property
    def cluster_window_size(self) -> int | None: ...
    @property
    def cluster_threshold(self) -> int | None: ...
    @property
    def legal_move_radius(self) -> int: ...
    @property
    def n_planes(self) -> int: ...
    @property
    def plane_layout(self) -> list[str]: ...
    @property
    def policy_logit_count(self) -> int: ...
    @property
    def has_pass_slot(self) -> bool: ...
    @property
    def is_multi_window(self) -> bool: ...
    @property
    def value_pool(self) -> str: ...
    @property
    def policy_pool(self) -> str: ...
    @property
    def sym_table_id(self) -> str: ...
    @property
    def schema_version(self) -> int: ...
    @property
    def notes(self) -> str: ...
    @property
    def kept_plane_indices(self) -> list[int]: ...
    @property
    def n_source_planes(self) -> int: ...
    @property
    def k_max(self) -> int: ...
    @property
    def representation(self) -> str: ...
    @property
    def is_graph(self) -> bool: ...
    @property
    def node_feat_dim(self) -> int | None: ...
    @property
    def edge_feat_dim(self) -> int | None: ...
    @property
    def win_length(self) -> int | None: ...
    @property
    def graph_radius(self) -> int | None: ...
    @property
    def win_axes(self) -> int | None: ...
    @property
    def contract_version(self) -> int | None: ...
    # derived accessors
    @property
    def n_actions(self) -> int: ...
    @property
    def n_cells(self) -> int: ...
    @property
    def state_stride(self) -> int: ...
    @property
    def chain_stride(self) -> int: ...
    @property
    def aux_stride(self) -> int: ...
    @property
    def policy_stride(self) -> int: ...
    def __repr__(self) -> str: ...
    @classmethod
    def from_registry(cls, name: str) -> RegistrySpec: ...

# --------------------------------------------------------------------------- #
# MCTSTree (unsendable)
# --------------------------------------------------------------------------- #
class MCTSTree:
    def __init__(
        self,
        c_puct: float = 1.5,
        virtual_loss: float = 1.0,
        fpu_reduction: float = 0.25,
        quiescence_enabled: bool = True,
        quiescence_blend_2: float = 0.3,
    ) -> None: ...
    def configure_search(
        self, kind: str, c_visit: float, c_scale: float, q_rescale: bool
    ) -> None:
        """Select the search kind and its σ. Raises ValueError on an unknown kind (never
        defaults)."""
    @property
    def search_kind(self) -> str: ...
    @property
    def search_sigma(self) -> tuple[float, float, bool]:
        """`(c_visit, c_scale, q_rescale)` as `configure_search` set them."""
    def gumbel_root_begin(self, m: int, budget: int, seed: int) -> None:
        """Draw this search's Gumbel root state over the expanded root, from an explicit
        seed. Raises RuntimeError when the root is not expanded."""
    def gumbel_root_select(self) -> int | None:
        """Under the configured σ. Raises RuntimeError when no root state has been drawn."""
    def gumbel_root_best_move(self) -> tuple[int, int] | None:
        """Under the configured σ. Raises RuntimeError when no root state has been drawn."""
    @property
    def quiescence_fire_count(self) -> int: ...
    def new_game(self, board: Board) -> None: ...
    def select_leaves(self, n: int) -> list[Board]:
        """Raises:
        SelectionDesync: the tree and the board disagree about what has been played.
        """
    def select_leaves_forced(self, children: list[int]) -> list[Board]:
        """One leaf per forced root child, no transposition fast path (A-1). Raises ValueError
        for a child the root does not own, SelectionDesync on a tree/board disagreement."""
        ...
    def expand_and_backup(
        self, policies: list[list[float]], values: list[float]
    ) -> None: ...
    def expand_and_backup_ls_graph(
        self,
        policies: list[list[float]],
        overflows: list[list[tuple[tuple[int, int], float]]],
        values: list[float],
        centers: list[tuple[int, int]],
        policy_stride: int,
        trunk_sz: int,
    ) -> None: ...
    def root_visits(self) -> int: ...
    def reset(self) -> None: ...
    def apply_dirichlet_to_root(
        self, noise: list[float], epsilon: float = 0.25
    ) -> None: ...
    def root_n_children(self) -> int: ...
    def get_top_visits(
        self, n: int
    ) -> list[tuple[tuple[int, int], int, float, float]]: ...
    def root_value(self) -> float: ...
    @property
    def forced_root_child(self) -> int | None: ...
    @forced_root_child.setter
    def forced_root_child(self, val: int | None) -> None: ...
    def get_root_children_info(
        self,
    ) -> list[tuple[tuple[int, int], int, float, int, float]]: ...
    def get_improved_policy(self, board_size: int | None = None) -> numpy.ndarray: ...

# --------------------------------------------------------------------------- #
# TacticalSolver
# --------------------------------------------------------------------------- #
class TacticalSolver:
    def __init__(
        self,
        window_half: int | None = 9,
        cand_cap: int = 40,
        neighbor_dist: int | None = None,
    ) -> None: ...
    def prove(
        self, board: Board, depth: int, node_budget: int
    ) -> tuple[int, list[tuple[int, int]], int]: ...

# --------------------------------------------------------------------------- #
# InferenceBatcher (the fused-model NN face over the graph queue)
# --------------------------------------------------------------------------- #
class InferenceBatcher:
    def __init__(self, encoding_spec: RegistrySpec, max_in_flight: int = 0) -> None: ...
    @property
    def graph_max_in_flight(self) -> int: ...
    @property
    def lock_recoveries(self) -> int: ...
    @property
    def policy_len_py(self) -> int: ...
    @property
    def representation_py(self) -> str: ...
    def close(self) -> None: ...
    def bump_model_version(self) -> int: ...
    @property
    def model_version(self) -> int: ...
    def has_pending_graph_requests(self) -> bool: ...
    def completed_graph_games(self) -> int: ...
    def check_graph_request(
        self,
        stones: list[tuple[int, int, int]],
        current_player: int,
        moves_remaining: int,
    ) -> None: ...
    def spawn_mock_graph_games(self, n_games: int) -> None: ...
    def next_graph_batch(
        self, batch_size: int, max_wait_ms: int = 10
    ) -> tuple[list[int], GraphWire]: ...
    def submit_graph_inference_results(
        self,
        request_ids: list[int],
        legal_probs_flat: numpy.ndarray,
        legal_offsets: numpy.ndarray,
        values: numpy.ndarray,
    ) -> None: ...
    def submit_graph_inference_failure(
        self, request_ids: list[int], error_msg: str
    ) -> None: ...
    def submit_graphs_and_wait(
        self,
        positions: list[tuple[list[tuple[int, int, int]], int, int]],
        n_threads: int = 1,
    ) -> list[tuple[list[float], list[tuple[tuple[int, int], float]], float]]: ...
    def submit_graphs_and_wait_ls(
        self,
        positions: list[tuple[list[tuple[int, int, int]], int, int]],
        n_threads: int = 1,
    ) -> list[
        tuple[list[float], list[tuple[tuple[int, int], float]], float, tuple[int, int]]
    ]: ...

# --------------------------------------------------------------------------- #
# GraphWire (block-diagonal fused graph batch; per-array COPY getters + take())
# --------------------------------------------------------------------------- #
class GraphWire:
    @property
    def contract_version(self) -> int: ...
    @property
    def builder_impl(self) -> int: ...
    @property
    def n_graphs(self) -> int: ...
    @property
    def node_feat(self) -> numpy.ndarray: ...
    @property
    def node_coords(self) -> numpy.ndarray: ...
    @property
    def edge_index(self) -> numpy.ndarray: ...
    @property
    def edge_attr(self) -> numpy.ndarray: ...
    @property
    def node_offsets(self) -> numpy.ndarray: ...
    @property
    def edge_offsets(self) -> numpy.ndarray: ...
    @property
    def legal_offsets(self) -> numpy.ndarray: ...
    @property
    def legal_node_gather(self) -> numpy.ndarray: ...
    @property
    def policy_dst_slot(self) -> numpy.ndarray: ...
    @property
    def n_nodes_checksum(self) -> numpy.ndarray: ...
    @property
    def n_stones(self) -> numpy.ndarray: ...
    @property
    def window_center(self) -> numpy.ndarray: ...
    @property
    def current_player(self) -> numpy.ndarray: ...
    def take(self) -> dict[str, Any]: ...

# --------------------------------------------------------------------------- #
# SelfPlayRunnerConfig
# --------------------------------------------------------------------------- #
class SelfPlayRunnerConfig:
    def __init__(
        self,
        n_workers: int = 4,
        max_moves_per_game: int = 128,
        n_simulations: int = 50,
        leaf_batch_size: int = 8,
        c_puct: float = 1.5,
        fpu_reduction: float = 0.25,
        fast_prob: float = 0.0,
        fast_sims: int = 50,
        standard_sims: int = 0,
        temp_threshold_compound_moves: int = 0,
        draw_reward: float = -0.1,
        ply_cap_value: float = -0.1,
        quiescence_enabled: bool = True,
        quiescence_blend_2: float = 0.3,
        temp_min: float = 0.5,
        c_visit: float = 50.0,
        c_scale: float = 1.0,
        *,
        q_rescale: bool,
        search_stats_every: int,
        gumbel_m: int = 16,
        gumbel_explore_moves: int = 10,
        dirichlet_alpha: float = 0.3,
        dirichlet_epsilon: float = 0.25,
        dirichlet_enabled: bool = True,
        results_queue_cap: int = 10_000,
        full_search_prob: float = 0.0,
        n_sims_quick: int = 0,
        n_sims_full: int = 0,
        random_opening_plies: int = 0,
        encoding_name: str | None = None,
    ) -> None: ...
    @property
    def search_kind(self) -> str: ...
    @search_kind.setter
    def search_kind(self, v: str) -> None: ...

# --------------------------------------------------------------------------- #
# SelfPlayRunner
# --------------------------------------------------------------------------- #
class SelfPlayRunner:
    def __init__(self, config: SelfPlayRunnerConfig) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def is_running(self) -> bool: ...
    def collect_graph_data(
        self,
    ) -> list[
        tuple[
            list[tuple[int, int, int]],
            list[tuple[int, int, float]],
            int,
            int,
            int,
            bool,
            float,
            bool,
            int,
            float,
            int,
        ]
    ]: ...
    @property
    def batcher(self) -> InferenceBatcher: ...
    @property
    def games_completed(self) -> int: ...
    @property
    def positions_generated(self) -> int: ...
    @property
    def x_wins(self) -> int: ...
    @property
    def o_wins(self) -> int: ...
    @property
    def draws(self) -> int: ...
    @property
    def positions_dropped(self) -> int: ...
    def get_win_stats(self) -> tuple[int, int, int]: ...
    @property
    def mcts_mean_depth(self) -> float: ...
    @property
    def mcts_mean_root_concentration(self) -> float: ...
    @property
    def mcts_quiescence_fires(self) -> int: ...
    @property
    def pcr_full_moves(self) -> int: ...
    @property
    def pcr_quick_moves(self) -> int: ...
    @property
    def gumbel_round_leaves(self) -> int: ...
    @property
    def gumbel_rounds(self) -> int: ...
    @property
    def max_sims_per_search(self) -> int: ...
    @property
    def export_offwindow_mass_moves(self) -> int: ...
    @property
    def target_integrity_defects(self) -> int: ...
    @property
    def inference_failures_total(self) -> int: ...
    @property
    def worker_panics(self) -> int: ...
    def drain_game_results(
        self,
    ) -> list[
        tuple[
            int, int, list[tuple[int, int]], int, int, int, int, int, list[tuple[int, bool]],
            list[tuple[int, float, float | None, list[tuple[tuple[int, int], int, float, float]]]] | None,
        ]
    ]: ...
    @property
    def model_version(self) -> int: ...
    def set_model_version(self, version: int) -> None: ...

# --------------------------------------------------------------------------- #
# HexgBuffer (HEXG graph replay) + GraphTargets
# --------------------------------------------------------------------------- #
class HexgBuffer:
    def __init__(self, capacity: int, encoding: str, visit_capacity: int) -> None: ...
    def push_graph_position(
        self,
        stones: list[tuple[int, int, int]],
        visits: list[tuple[int, int, float]],
        current_player: int,
        moves_remaining: int,
        ply_index: int,
        is_full_search: bool,
        outcome: float,
        value_valid: bool,
        game_length: int,
        game_id: int = -1,
        tail_mass: float = 0.0,
    ) -> None: ...
    def sample_graph_batch(
        self,
        batch_size: int,
        augment: bool = False,
        recent_frac: float = 0.0,
        n_threads: int = 1,
    ) -> tuple[GraphWire, GraphTargets]: ...
    def resize(self, new_capacity: int) -> None: ...
    def get_buffer_stats(self) -> tuple[int, int, list[int]]: ...
    def seed_sampler(self, seed: int) -> None: ...
    def next_game_id(self) -> int: ...
    def game_id_at(self, index: int) -> int: ...
    def last_batch_composition(self) -> dict[str, int]: ...
    def sym_draw_counts(self) -> tuple[list[int], int]: ...
    def samples_consumed_total(self) -> int: ...
    def save_to_path(self, path: str) -> None: ...
    def load_from_path(self, path: str) -> int: ...
    @property
    def size(self) -> int: ...
    @property
    def capacity(self) -> int: ...
    @property
    def visit_capacity(self) -> int: ...
    @property
    def encoding_name(self) -> str: ...
    @property
    def lock_recoveries(self) -> int: ...

class GraphTargets:
    @property
    def policy_target(self) -> numpy.ndarray: ...
    @property
    def explicit_mask(self) -> numpy.ndarray: ...
    @property
    def tail_mass(self) -> numpy.ndarray: ...
    @property
    def outcomes(self) -> numpy.ndarray: ...
    @property
    def value_valid(self) -> numpy.ndarray: ...
    @property
    def is_full_search(self) -> numpy.ndarray: ...
    @property
    def target_argmax_cells(self) -> list[tuple[int, int] | None]: ...

# --------------------------------------------------------------------------- #
# Free functions
# --------------------------------------------------------------------------- #
def verify_edge_geometry(
    node_feat: numpy.ndarray,
    node_coords: numpy.ndarray,
    edge_index: numpy.ndarray,
    edge_attr: numpy.ndarray,
    node_offsets: numpy.ndarray,
    current_player: numpy.ndarray,
    node_feat_dim: int,
    edge_feat_dim: int,
    win_length: int,
) -> None: ...
def mcts_pool_overflow_count() -> int: ...
def mcts_max_armed_sims() -> int:
    """The largest sim budget the MCTS node pool can serve (AUDIT-1 F-21).

    `MAX_NODES / (4 * MAX_CHILDREN_PER_NODE)`, derived in `mantis-search`. The config schema
    reads it across the bridge rather than re-typing the number, so the bound cannot go stale
    when either constant moves.
    """
def mcts_max_armed_sims_gumbel() -> int:
    """The same bound under `search.kind: gumbel`.

    `(MAX_NODES - MAX_ROOT_CHILDREN) / (4 * MAX_CHILDREN_PER_NODE)`. That kind reaches the
    root's full legal set, so it spends `MAX_ROOT_CHILDREN` slots on the root instead of
    `MAX_CHILDREN_PER_NODE` and its ceiling is the lower of the two. Read across the bridge
    for the same reason as its sibling: the schema refuses an over-budget config at MINT,
    and it cannot do that against a number it does not have.
    """

def take_mcts_pool_overflow_count() -> int: ...
def graph_row_outcome(
    rec_player: int,
    winner: int,
    terminal_reason: int,
    ply_cap_value: float,
    draw_reward: float,
) -> tuple[float, int]: ...

# --------------------------------------------------------------------------- #
# Module functions (encoding registry — NEW-BUILD, LOCKED #8)
# --------------------------------------------------------------------------- #
def all_specs() -> list[RegistrySpec]: ...
def max_stones() -> int: ...
def registry_sha() -> bytes: ...
def registry_sha_hex() -> str: ...

def derived_hexg_visit_capacity(
    n_simulations: int,
    standard_sims: int,
    fast_prob: float,
    fast_sims: int,
    full_search_prob: float,
    n_sims_quick: int,
    n_sims_full: int,
    leaf_batch_size: int,
    gumbel_m: int,
    search_kind: str,
) -> int: ...


# ── wire-format geometry constants (AUDIT-1 F-42) ──────────────────────────────────────
# Owners `mantis_core::board::{HEX_AXES, WIN_LENGTH, DEFAULT_CLUSTER_THRESHOLD}`; the
# cross-check is `tests/encoding/test_geometry_crosses_the_ffi.py`.
HEX_AXES: tuple[tuple[int, int], tuple[int, int], tuple[int, int]]
WIN_LENGTH: int
DEFAULT_CLUSTER_THRESHOLD: int
