"""Typed surface of the compiled mantis._engine extension (crates/mantis-bridge).

Twin of src/mantis/_engine.pyi (the type-checker-visible copy in the editable src
package). This copy ships in the mantis-engine wheel beside the compiled module and
also keeps the PEP 420 namespace dir (python/mantis/) tracked so fresh clones build.
>300 justify (R8): a 1:1 typed mirror of the compiled mantis._engine surface (11 pyclasses + free functions) — its length is the bridge API's, and a module stub cannot be split.
Keep both stubs identical when the bridge API changes.

Generated for the WP7 assembly: 11 pyclasses + 4 free fns + 3 module fns +
WireAlreadyConsumed, all resolving on `mantis._engine`. Numpy arrays are typed as
`numpy.ndarray` (dtype/shape documented in docstrings on the Rust side).
"""

from typing import Any

import numpy

# --------------------------------------------------------------------------- #
# Exceptions
# --------------------------------------------------------------------------- #
class WireAlreadyConsumed(Exception):
    """Raised when GraphWire.take() is called a second time (single-read latch)."""

# --------------------------------------------------------------------------- #
# Board (unsendable — single-thread Python ownership)
# --------------------------------------------------------------------------- #
class Board:
    def __init__(self) -> None: ...
    @staticmethod
    def with_encoding_name(name: str) -> Board: ...
    def apply_move(self, q: int, r: int) -> None: ...
    def check_win(self) -> bool: ...
    def winner(self) -> int | None: ...
    def find_winning_line(self) -> list[tuple[int, int]]: ...
    def terminal_value_to_move(self) -> float: ...
    def count_winning_moves(self, player: int) -> int: ...
    def winning_moves(self, player: int) -> list[tuple[int, int]]: ...
    def first_winning_move(self, player: int) -> tuple[int, int] | None: ...
    def has_player_long_run(self, player: int, min_len: int) -> bool: ...
    def threat_moves(self, player: int) -> list[tuple[int, int]]: ...
    def forced_win_move(self, depth: int) -> tuple[int, int] | None: ...
    def legal_moves(self) -> list[tuple[int, int]]: ...
    def legal_move_count(self) -> int: ...
    def get(self, q: int, r: int) -> int: ...
    @property
    def current_player(self) -> int: ...
    @property
    def moves_remaining(self) -> int: ...
    @property
    def ply(self) -> int: ...
    def set_legal_move_radius(self, radius: int) -> None: ...
    def legal_move_radius(self) -> int: ...
    def zobrist_hash(self) -> int: ...
    def to_tensor(self) -> numpy.ndarray: ...
    def get_cluster_views(self) -> tuple[list[numpy.ndarray], list[tuple[int, int]]]: ...
    def set_cluster_threshold(self, threshold: int) -> None: ...
    def cluster_threshold(self) -> int: ...
    def set_cluster_window_size(self, size: int) -> None: ...
    def cluster_window_size(self) -> int: ...
    def to_flat(self, q: int, r: int) -> int: ...
    @property
    def size(self) -> int: ...
    def get_threats(self) -> list[tuple[int, int, int, int]]: ...
    def get_stones(self) -> list[tuple[int, int, int]]: ...
    def clone(self) -> Board: ...
    def __copy__(self) -> Board: ...
    def __deepcopy__(self, memo: Any) -> Board: ...
    def __repr__(self) -> str: ...

# --------------------------------------------------------------------------- #
# RegistrySpec (encoding schema view over &'static RegistrySpec)
# --------------------------------------------------------------------------- #
class RegistrySpec:
    @property
    def name(self) -> str: ...
    @property
    def board_size(self) -> int: ...
    @property
    def trunk_size(self) -> int: ...
    @property
    def cluster_window_size(self) -> int | None: ...
    @property
    def cluster_threshold(self) -> int | None: ...
    @property
    def legal_move_radius(self) -> int: ...
    @property
    def n_planes(self) -> int: ...
    @property
    def plane_layout(self) -> list[str]: ...
    @property
    def policy_logit_count(self) -> int: ...
    @property
    def has_pass_slot(self) -> bool: ...
    @property
    def is_multi_window(self) -> bool: ...
    @property
    def value_pool(self) -> str: ...
    @property
    def policy_pool(self) -> str: ...
    @property
    def sym_table_id(self) -> str: ...
    @property
    def schema_version(self) -> int: ...
    @property
    def notes(self) -> str: ...
    @property
    def kept_plane_indices(self) -> list[int]: ...
    @property
    def n_source_planes(self) -> int: ...
    @property
    def k_max(self) -> int: ...
    @property
    def representation(self) -> str: ...
    @property
    def is_graph(self) -> bool: ...
    @property
    def node_feat_dim(self) -> int | None: ...
    @property
    def edge_feat_dim(self) -> int | None: ...
    @property
    def win_length(self) -> int | None: ...
    @property
    def graph_radius(self) -> int | None: ...
    @property
    def win_axes(self) -> int | None: ...
    @property
    def contract_version(self) -> int | None: ...
    @property
    def builder_impl_required(self) -> int | None: ...
    # derived accessors
    @property
    def n_actions(self) -> int: ...
    @property
    def n_cells(self) -> int: ...
    @property
    def state_stride(self) -> int: ...
    @property
    def chain_stride(self) -> int: ...
    @property
    def aux_stride(self) -> int: ...
    @property
    def policy_stride(self) -> int: ...
    def __repr__(self) -> str: ...
    @classmethod
    def from_registry(cls, name: str) -> RegistrySpec: ...

# --------------------------------------------------------------------------- #
# MCTSTree (unsendable)
# --------------------------------------------------------------------------- #
class MCTSTree:
    def __init__(
        self,
        c_puct: float = 1.5,
        virtual_loss: float = 1.0,
        fpu_reduction: float = 0.25,
        quiescence_enabled: bool = True,
        quiescence_blend_2: float = 0.3,
    ) -> None: ...
    @property
    def quiescence_fire_count(self) -> int: ...
    def last_search_stats(self) -> tuple[float, float]: ...
    def new_game(self, board: Board) -> None: ...
    def select_leaves(self, n: int) -> list[Board]: ...
    def expand_and_backup(
        self, policies: list[list[float]], values: list[float]
    ) -> None: ...
    def expand_and_backup_ls(
        self,
        policies: list[list[float]],
        values: list[float],
        leaf_k: list[int],
        policy_stride: int,
        has_pass_slot: bool,
        trunk_sz: int,
    ) -> None: ...
    def get_policy(
        self, temperature: float = 1.0, board_size: int | None = None
    ) -> numpy.ndarray: ...
    def root_visits(self) -> int: ...
    def reset(self) -> None: ...
    def run_simulations_cpu_only(self, n: int) -> None: ...
    def apply_dirichlet_to_root(
        self, noise: list[float], epsilon: float = 0.25
    ) -> None: ...
    def root_n_children(self) -> int: ...
    def get_top_visits(
        self, n: int
    ) -> list[tuple[tuple[int, int], int, float, float]]: ...
    def root_value(self) -> float: ...
    @property
    def forced_root_child(self) -> int | None: ...
    @forced_root_child.setter
    def forced_root_child(self, val: int | None) -> None: ...
    def get_root_children_info(
        self,
    ) -> list[tuple[tuple[int, int], int, float, int, float]]: ...
    def get_improved_policy(
        self,
        board_size: int | None = None,
        c_visit: float = 50.0,
        c_scale: float = 1.0,
    ) -> numpy.ndarray: ...

# --------------------------------------------------------------------------- #
# TacticalSolver
# --------------------------------------------------------------------------- #
class TacticalSolver:
    def __init__(
        self,
        window_half: int | None = 9,
        cand_cap: int = 40,
        neighbor_dist: int | None = None,
    ) -> None: ...
    def prove(
        self, board: Board, depth: int, node_budget: int
    ) -> tuple[int, list[tuple[int, int]], int]: ...

# --------------------------------------------------------------------------- #
# InferenceBatcher (21-method fused-model NN face over the dense+graph queues)
# --------------------------------------------------------------------------- #
class InferenceBatcher:
    def __init__(
        self,
        encoding_spec: RegistrySpec | None = None,
        feature_len: int | None = None,
        policy_len: int | None = None,
        pool_size: int | None = None,
    ) -> None: ...
    def spawn_mock_games(self, n_games: int) -> None: ...
    def completed_mock_games(self) -> int: ...
    def has_pending_requests(self) -> bool: ...
    def next_inference_batch(
        self, batch_size: int, max_wait_ms: int = 10
    ) -> tuple[list[int], numpy.ndarray]: ...
    def submit_inference_results(
        self,
        request_ids: list[int],
        policies: numpy.ndarray,
        values: numpy.ndarray,
    ) -> None: ...
    def submit_inference_failure(
        self, request_ids: list[int], error_msg: str
    ) -> None: ...
    def close(self) -> None: ...
    def bump_model_version(self) -> int: ...
    @property
    def model_version(self) -> int: ...
    @property
    def feature_len_py(self) -> int: ...
    @property
    def policy_len_py(self) -> int: ...
    @property
    def representation_py(self) -> str: ...
    def has_pending_graph_requests(self) -> bool: ...
    def completed_graph_games(self) -> int: ...
    def check_graph_request(
        self,
        stones: list[tuple[int, int, int]],
        current_player: int,
        moves_remaining: int,
    ) -> None: ...
    def spawn_mock_graph_games(self, n_games: int) -> None: ...
    def next_graph_batch(
        self, batch_size: int, max_wait_ms: int = 10
    ) -> tuple[list[int], GraphWire]: ...
    def submit_graph_inference_results(
        self,
        request_ids: list[int],
        legal_probs_flat: numpy.ndarray,
        legal_offsets: numpy.ndarray,
        values: numpy.ndarray,
    ) -> None: ...
    def submit_graph_inference_failure(
        self, request_ids: list[int], error_msg: str
    ) -> None: ...
    def submit_graphs_and_wait(
        self, positions: list[tuple[list[tuple[int, int, int]], int, int]]
    ) -> list[tuple[list[float], list[tuple[tuple[int, int], float]], float]]: ...

# --------------------------------------------------------------------------- #
# GraphWire (block-diagonal fused graph batch; per-array COPY getters + take())
# --------------------------------------------------------------------------- #
class GraphWire:
    @property
    def contract_version(self) -> int: ...
    @property
    def builder_impl(self) -> int: ...
    @property
    def n_graphs(self) -> int: ...
    @property
    def node_feat(self) -> numpy.ndarray: ...
    @property
    def node_coords(self) -> numpy.ndarray: ...
    @property
    def edge_index(self) -> numpy.ndarray: ...
    @property
    def edge_attr(self) -> numpy.ndarray: ...
    @property
    def node_offsets(self) -> numpy.ndarray: ...
    @property
    def edge_offsets(self) -> numpy.ndarray: ...
    @property
    def legal_offsets(self) -> numpy.ndarray: ...
    @property
    def legal_node_gather(self) -> numpy.ndarray: ...
    @property
    def policy_dst_slot(self) -> numpy.ndarray: ...
    @property
    def n_nodes_checksum(self) -> numpy.ndarray: ...
    @property
    def n_stones(self) -> numpy.ndarray: ...
    @property
    def window_center(self) -> numpy.ndarray: ...
    @property
    def current_player(self) -> numpy.ndarray: ...
    def take(self) -> dict[str, Any]: ...

# --------------------------------------------------------------------------- #
# SelfPlayRunnerConfig
# --------------------------------------------------------------------------- #
class SelfPlayRunnerConfig:
    def __init__(
        self,
        n_workers: int = 4,
        max_moves_per_game: int = 128,
        n_simulations: int = 50,
        leaf_batch_size: int = 8,
        c_puct: float = 1.5,
        fpu_reduction: float = 0.25,
        fast_prob: float = 0.0,
        fast_sims: int = 50,
        standard_sims: int = 0,
        temp_threshold_compound_moves: int = 0,
        draw_reward: float = -0.1,
        ply_cap_value: float = -0.1,
        quiescence_enabled: bool = True,
        quiescence_blend_2: float = 0.3,
        temp_min: float = 0.5,
        zoi_enabled: bool = False,
        zoi_lookback: int = 16,
        zoi_margin: int = 5,
        completed_q_values: bool = False,
        c_visit: float = 50.0,
        c_scale: float = 1.0,
        gumbel_mcts: bool = False,
        gumbel_m: int = 16,
        gumbel_explore_moves: int = 10,
        dirichlet_alpha: float = 0.3,
        dirichlet_epsilon: float = 0.25,
        dirichlet_enabled: bool = True,
        results_queue_cap: int = 10_000,
        full_search_prob: float = 0.0,
        n_sims_quick: int = 0,
        n_sims_full: int = 0,
        random_opening_plies: int = 0,
        selfplay_rotation_enabled: bool = False,
        encoding_name: str | None = None,
        inference_pool_size: int | None = None,
    ) -> None: ...
    @property
    def forced_win_policy_enabled(self) -> bool: ...
    @forced_win_policy_enabled.setter
    def forced_win_policy_enabled(self, v: bool) -> None: ...
    @property
    def forced_win_policy_depth(self) -> int: ...
    @forced_win_policy_depth.setter
    def forced_win_policy_depth(self, v: int) -> None: ...
    @property
    def forced_win_policy_weight(self) -> float: ...
    @forced_win_policy_weight.setter
    def forced_win_policy_weight(self, v: float) -> None: ...
    @property
    def solver_enabled(self) -> bool: ...
    @solver_enabled.setter
    def solver_enabled(self, v: bool) -> None: ...
    @property
    def solver_depth(self) -> int: ...
    @solver_depth.setter
    def solver_depth(self, v: int) -> None: ...
    @property
    def solver_node_budget(self) -> int: ...
    @solver_node_budget.setter
    def solver_node_budget(self, v: int) -> None: ...
    @property
    def solver_neighbor_dist(self) -> int: ...
    @solver_neighbor_dist.setter
    def solver_neighbor_dist(self, v: int) -> None: ...
    @property
    def solver_visit_weight(self) -> float: ...
    @solver_visit_weight.setter
    def solver_visit_weight(self, v: float) -> None: ...
    @property
    def seed_fraction(self) -> float: ...
    @seed_fraction.setter
    def seed_fraction(self, v: float) -> None: ...
    @property
    def seed_corpus(self) -> list[list[tuple[int, int]]] | None: ...
    @seed_corpus.setter
    def seed_corpus(self, v: list[list[tuple[int, int]]] | None) -> None: ...

# --------------------------------------------------------------------------- #
# SelfPlayRunner
# --------------------------------------------------------------------------- #
class SelfPlayRunner:
    def __init__(self, config: SelfPlayRunnerConfig) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def is_running(self) -> bool: ...
    def collect_data(
        self,
    ) -> tuple[
        numpy.ndarray,
        numpy.ndarray,
        numpy.ndarray,
        numpy.ndarray,
        numpy.ndarray,
        numpy.ndarray,
        numpy.ndarray,
        numpy.ndarray,
        numpy.ndarray,
        numpy.ndarray,
    ]: ...
    def collect_graph_data(
        self,
    ) -> list[
        tuple[
            list[tuple[int, int, int]],
            list[tuple[int, int, float]],
            int,
            int,
            int,
            bool,
            float,
            bool,
            int,
        ]
    ]: ...
    @property
    def batcher(self) -> InferenceBatcher: ...
    def feature_len(self) -> int: ...
    def policy_len(self) -> int: ...
    @property
    def games_completed(self) -> int: ...
    @property
    def positions_generated(self) -> int: ...
    @property
    def x_wins(self) -> int: ...
    @property
    def o_wins(self) -> int: ...
    @property
    def draws(self) -> int: ...
    @property
    def positions_dropped(self) -> int: ...
    def get_win_stats(self) -> tuple[int, int, int]: ...
    @property
    def mcts_mean_depth(self) -> float: ...
    @property
    def mcts_mean_root_concentration(self) -> float: ...
    @property
    def mcts_quiescence_fires(self) -> int: ...
    @property
    def cluster_value_std_mean(self) -> float: ...
    @property
    def cluster_policy_disagreement_mean(self) -> float: ...
    @property
    def cluster_variance_sample_count(self) -> int: ...
    @property
    def solver_moves_eligible(self) -> int: ...
    @property
    def solver_win_proven(self) -> int: ...
    @property
    def solver_injected(self) -> int: ...
    @property
    def solver_injected_offwindow(self) -> int: ...
    @property
    def solver_budget_exhausted(self) -> int: ...
    @property
    def solver_moves_eligible_seeded(self) -> int: ...
    @property
    def solver_injected_seeded(self) -> int: ...
    @property
    def seeded_games_started(self) -> int: ...
    def drain_game_results(
        self,
    ) -> list[
        tuple[int, int, list[tuple[int, int]], int, int, int, int, int, int, int]
    ]: ...
    @property
    def model_version(self) -> int: ...
    def set_model_version(self, version: int) -> None: ...

# --------------------------------------------------------------------------- #
# ReplayBuffer (HEXB dense replay)
# --------------------------------------------------------------------------- #
class ReplayBuffer:
    def __init__(self, capacity: int, encoding: str) -> None: ...
    def get_buffer_stats(self) -> tuple[int, int, list[int]]: ...
    def next_game_id(self) -> int: ...
    def push(
        self,
        state: numpy.ndarray,
        chain_planes: numpy.ndarray,
        policy: numpy.ndarray,
        outcome: float,
        ownership: numpy.ndarray,
        winning_line: numpy.ndarray,
        game_id: int = -1,
        game_length: int = 0,
        is_full_search: bool = True,
        position_index: int = 0,
        value_target_valid: bool = True,
    ) -> None: ...
    def push_game(
        self,
        states: numpy.ndarray,
        chain_planes: numpy.ndarray,
        policies: numpy.ndarray,
        outcomes: numpy.ndarray,
        ownership: numpy.ndarray,
        winning_line: numpy.ndarray,
        game_id: int = -1,
        game_length: int = 0,
        is_full_search: numpy.ndarray | None = None,
        position_indices: numpy.ndarray | None = None,
        value_target_valid: numpy.ndarray | None = None,
    ) -> None: ...
    def push_many(
        self,
        states: numpy.ndarray,
        chain_planes: numpy.ndarray,
        policies: numpy.ndarray,
        outcomes: numpy.ndarray,
        ownership: numpy.ndarray,
        winning_line: numpy.ndarray,
        game_lengths: numpy.ndarray,
        is_full_search: numpy.ndarray,
        position_indices: numpy.ndarray | None = None,
        value_target_valid: numpy.ndarray | None = None,
    ) -> None: ...
    def sample_batch(
        self, batch_size: int, augment: bool
    ) -> tuple[
        numpy.ndarray,
        numpy.ndarray,
        numpy.ndarray,
        numpy.ndarray,
        numpy.ndarray,
        numpy.ndarray,
        numpy.ndarray,
        numpy.ndarray,
    ]: ...
    def sample_batch_with_pos(
        self, batch_size: int, augment: bool
    ) -> tuple[
        numpy.ndarray,
        numpy.ndarray,
        numpy.ndarray,
        numpy.ndarray,
        numpy.ndarray,
        numpy.ndarray,
        numpy.ndarray,
        numpy.ndarray,
        numpy.ndarray,
    ]: ...
    def resize(self, new_capacity: int) -> None: ...
    def outcome_in_range_count(self, lo: float, hi: float) -> int: ...
    def set_weight_schedule(
        self, thresholds: list[int], weights: list[float], default_weight: float
    ) -> None: ...
    def save_to_path(self, path: str) -> None: ...
    def load_from_path(self, path: str) -> int: ...
    @property
    def size(self) -> int: ...
    @property
    def capacity(self) -> int: ...
    @property
    def encoding(self) -> RegistrySpec: ...

# --------------------------------------------------------------------------- #
# HexgBuffer (HEXG graph replay) + GraphTargets
# --------------------------------------------------------------------------- #
class HexgBuffer:
    def __init__(self, capacity: int, encoding: str) -> None: ...
    def push_graph_position(
        self,
        stones: list[tuple[int, int, int]],
        visits: list[tuple[int, int, float]],
        current_player: int,
        moves_remaining: int,
        ply_index: int,
        is_full_search: bool,
        outcome: float,
        value_valid: bool,
        game_length: int,
        game_id: int = -1,
    ) -> None: ...
    def sample_graph_batch(
        self, batch_size: int, augment: bool = False, recent_frac: float = 0.0
    ) -> tuple[GraphWire, GraphTargets]: ...
    def resize(self, new_capacity: int) -> None: ...
    def set_weight_schedule(
        self, thresholds: list[int], weights: list[float], default_weight: float
    ) -> None: ...
    def get_buffer_stats(self) -> tuple[int, int, list[int]]: ...
    def next_game_id(self) -> int: ...
    def save_to_path(self, path: str) -> None: ...
    def load_from_path(self, path: str) -> int: ...
    @property
    def size(self) -> int: ...
    @property
    def capacity(self) -> int: ...
    @property
    def encoding_name(self) -> str: ...

class GraphTargets:
    @property
    def policy_target(self) -> numpy.ndarray: ...
    @property
    def outcomes(self) -> numpy.ndarray: ...
    @property
    def value_valid(self) -> numpy.ndarray: ...
    @property
    def is_full_search(self) -> numpy.ndarray: ...
    @property
    def target_argmax_cells(self) -> list[tuple[int, int] | None]: ...

# --------------------------------------------------------------------------- #
# Free functions
# --------------------------------------------------------------------------- #
def verify_edge_geometry(
    node_feat: numpy.ndarray,
    node_coords: numpy.ndarray,
    edge_index: numpy.ndarray,
    edge_attr: numpy.ndarray,
    node_offsets: numpy.ndarray,
    current_player: numpy.ndarray,
    node_feat_dim: int,
    edge_feat_dim: int,
    win_length: int,
) -> None: ...
def apply_symmetries_batch(
    states: numpy.ndarray, sym_indices: list[int]
) -> numpy.ndarray: ...
def mcts_pool_overflow_count() -> int: ...
def take_mcts_pool_overflow_count() -> int: ...

# --------------------------------------------------------------------------- #
# Module functions (encoding registry — NEW-BUILD, LOCKED #8)
# --------------------------------------------------------------------------- #
def all_specs() -> list[RegistrySpec]: ...
def registry_sha() -> bytes: ...
def registry_sha_hex() -> str: ...
