"""R318(b) — the deploy head searches at the config's OWN `selfplay.leaf_batch_size`.

**THE DEFECT, measured at RECAL-SITTING-3.** `DeployHeadPlayer.select_move` called
`select_leaves(1)` — hardcoded — so a 128-sim move issued 128 BLOCKING single-board GPU
round-trips. Three independent SIGUSR1 stack samples of a live eval child landed in the
identical frame (`inference_local.infer_batch_ls` under `deploy_head.select_move`) while the
card sat at 5% and one CPU core was saturated: overhead-bound, not compute-bound. A 32-game
gate block is ~130 000 such round-trips, which is 22-44 minutes with the GPU otherwise IDLE and
hours under a 12-worker self-play load — the arithmetic that reproduces the observed
`games_total: 0` at `eval.round_timeout_sec` from first principles.

**WHY THE FIX IS AN ALIGNMENT AND NOT A CONCESSION (R318(b)(ii)).** The net's policy and value
targets are GENERATED by `k=8` leaf-batched self-play search (`selfplay/worker.py`'s
`select_leaves(current_batch)`). A deploy head searching at `k=1` was therefore an unexamined
TRAIN/DEPLOY MISMATCH, and matching the width is what makes eval deploy-matched by
construction rather than by assertion. Provenance: `select_leaves(1)` dates to `075ae35`
(WP11-A, the original eval+arena landing), so this predates every recent prep leg.

**WHAT THIS FILE PINS, and the mutation each row survives without:**
  - the round-trip COUNT falls to `ceil(n_sims / k)` — the mechanism the whole fix is for, and
    the one a reader would otherwise have to take on trust from a wall-clock number;
  - the NODE BUDGET is unchanged at `n_sims` for every `k` — R318(b)(iii)'s "fixed nodes",
    without which a faster search would simply be a WEAKER one and every gate comparison would
    silently change meaning;
  - `k = 1` still behaves exactly as the shipped head did, so the pre-R318 oracle set keeps
    pinning what it always pinned;
  - `leaf_batch_size` is REQUIRED and refuses `< 1` — a default would be a search regime nobody
    minted, and the value it would take (1) is the defect itself;
  - the deploy head and the self-play worker read the SAME config key, checked structurally, so
    the two regimes cannot silently fork again (R318 §2's own requirement).
"""
from __future__ import annotations

import ast
from pathlib import Path

import pytest

from mantis._engine import Board
from mantis.arena.deploy_head import DeployHeadPlayer

_REPO = Path(__file__).resolve().parents[2]
_ENCODING = "v6_live2_ls"
_POLICY_LEN = 362


def _counting_expand_fn(calls: list[int]):
    """An expand collaborator that RECORDS the batch width it was handed, per call."""
    def _expand(tree, leaves) -> None:
        calls.append(len(leaves))
        tree.expand_and_backup(
            [[0.0] * _POLICY_LEN for _ in leaves], [0.0] * len(leaves)
        )
    return _expand


def _counting_infer_fn(calls: list[int]):
    """The grid arm's per-leaf collaborator; one entry per LEAF, so the two arms' counts are
    directly comparable to the round-trip claim."""
    def _infer(_board):
        calls.append(1)
        return [0.0] * _POLICY_LEN, 0.0
    return _infer


def _play_one_move(*, n_sims: int, leaf_batch_size: int) -> list[int]:
    """One `select_move` on the GRAPH arm; returns the per-call batch widths."""
    calls: list[int] = []
    player = DeployHeadPlayer(
        expand_fn=_counting_expand_fn(calls), n_sims=n_sims, leaf_batch_size=leaf_batch_size,
    )
    player.new_game()
    player.select_move(Board.with_encoding_name(_ENCODING))
    return calls


# ── the mechanism: round-trips fall, node budget does not ────────────────────────────────
@pytest.mark.parametrize("k", [1, 2, 4, 8, 16, 128])
def test_the_node_budget_is_EXACTLY_n_sims_at_every_batch_width(k: int) -> None:
    """R318(b)(iii), FIXED NODES — the strongest row in this file.

    Without it the fix would be indistinguishable from simply searching LESS, and a self-play
    THROUGHPUT knob would silently move deploy STRENGTH: `select_leaves(k)` returns fewer than
    `k` on a cold tree (measured 1, 1, then k), so a budget credited by the REQUEST spends
    ~11% fewer nodes at k=8 than at k=1. This row is what forces the budget to advance by
    leaves actually returned, and it is exact — not a tolerance."""
    n_sims = 128
    calls = _play_one_move(n_sims=n_sims, leaf_batch_size=k)
    assert sum(calls) == n_sims, (
        f"leaf_batch_size={k} evaluated {sum(calls)} leaves against a budget of exactly "
        f"{n_sims} (widths {calls}). Batching changes how the budget is SPENT, never how much "
        f"of it is — otherwise the batch width is a hidden strength dial."
    )
    assert all(w <= k for w in calls), (
        f"no single request may exceed the batch width: widths {calls} at k={k}"
    )


def test_batching_COLLAPSES_the_round_trip_count_which_is_the_whole_fix() -> None:
    """THE MECHANISM R318(d)'s ~8x prediction rests on, pinned as a COUNT rather than a
    duration — a wall-clock assertion would be a benchmark, and this is the arithmetic.

    Compared against k=1 rather than against a hardcoded number, because the exact count
    depends on the tree's cold-start ramp (1, 1, then k) and pinning that would make this row
    a transcription of an implementation detail instead of the claim."""
    n_sims = 128
    at_1 = _play_one_move(n_sims=n_sims, leaf_batch_size=1)
    at_8 = _play_one_move(n_sims=n_sims, leaf_batch_size=8)

    assert len(at_1) == n_sims, f"k=1 must issue one round-trip per sim; got {len(at_1)}"
    assert sum(at_1) == sum(at_8) == n_sims, "both must spend the identical node budget"
    assert len(at_8) * 4 < len(at_1), (
        f"k=8 issued {len(at_8)} blocking round-trips against k=1's {len(at_1)} for the SAME "
        f"{n_sims} nodes. This collapse IS the fix: at k=1 a 128-sim move made 128 blocking "
        f"GPU round-trips, ~130k per gate block, which is the measured cause of "
        f"RECAL-SITTING-3's games_total: 0 inside a 3600 s budget."
    )


def test_a_short_final_batch_never_OVERSPENDS_the_budget() -> None:
    """The remainder case: `min(k, remaining)` must clamp the last request, or a move would
    quietly search past its own n_sims — the same fixed-nodes property from the other side."""
    calls = _play_one_move(n_sims=10, leaf_batch_size=4)
    assert sum(calls) == 10, f"10 nodes requested, {sum(calls)} evaluated (widths {calls})"


def test_k_equals_one_is_byte_for_byte_the_old_loop() -> None:
    """The pre-R318 oracle set was written against k=1 and still pins what it pinned: one leaf
    per call, exactly `n_sims` calls. If this row ever reds, every one of those tests has
    quietly changed subject."""
    calls = _play_one_move(n_sims=7, leaf_batch_size=1)
    assert calls == [1] * 7, f"k=1 must request one leaf per call, 7 times; got {calls}"


def test_the_grid_arm_batches_too_and_is_not_left_behind() -> None:
    """Both arms share the loop, so the grid arm must batch as well. It is asserted separately
    because the grid arm reaches the net through a PER-LEAF `infer_fn`: the leaf count stays
    `n_sims` there by construction, and what falls is the number of `select_leaves` round-trips
    the tree is driven through. A fix applied to only one arm would pass every graph-arm row."""
    calls: list[int] = []
    player = DeployHeadPlayer(
        infer_fn=_counting_infer_fn(calls), n_sims=12, leaf_batch_size=4,
    )
    player.new_game()
    player.select_move(Board.with_encoding_name(_ENCODING))
    assert sum(calls) == 12, (
        f"the grid arm must still evaluate every one of the 12 budgeted leaves; got {sum(calls)}. "
        f"The per-leaf infer_fn count is the node budget on this arm, and it is the same 12 the "
        f"graph arm spends — the arms differ in transport, never in how much they search."
    )


# ── the knob: required, validated, and SHARED with self-play ─────────────────────────────
@pytest.mark.parametrize("bad", [0, -1])
def test_a_batch_width_below_one_is_REFUSED_not_clamped(bad: int) -> None:
    """R1 applied to a search regime: a silent clamp to 1 would restore the exact defect this
    ruling exists to close, and it would do it invisibly."""
    with pytest.raises(ValueError, match="leaf_batch_size"):
        DeployHeadPlayer(infer_fn=_counting_infer_fn([]), n_sims=4, leaf_batch_size=bad)


def test_leaf_batch_size_has_NO_DEFAULT_and_must_be_stated() -> None:
    """A default here would be a search-regime constant nobody minted. The constructor must
    refuse to guess — omitting it is a TypeError, not a quiet k=1."""
    with pytest.raises(TypeError, match="leaf_batch_size"):
        DeployHeadPlayer(infer_fn=_counting_infer_fn([]), n_sims=4)  # type: ignore[call-arg]


def test_deploy_and_selfplay_read_THE_SAME_CONFIG_KEY() -> None:
    """R318 §2's own requirement, checked STRUCTURALLY (R296(f)) rather than by comparing two
    numbers that happen to agree today.

    The composition root must hand `build_eval_pipeline` the expression
    `config.selfplay.leaf_batch_size` — the very attribute the self-play hparams resolver reads
    (`hparams.py`: `leaf_batch_size=int(sp["leaf_batch_size"])`). A future edit that pointed
    eval at a NEW key, or at a literal, would leave both regimes green while forking them —
    which is precisely how the k=1/k=8 mismatch survived from 075ae35 to now.
    """
    tree = ast.parse((_REPO / "src" / "mantis" / "run.py").read_text(encoding="utf-8"))
    sources = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        func = node.func
        name = func.id if isinstance(func, ast.Name) else getattr(func, "attr", None)
        if name != "build_eval_pipeline":
            continue
        for kw in node.keywords:
            if kw.arg == "leaf_batch_size":
                sources.append(ast.unparse(kw.value))

    assert sources == ["config.selfplay.leaf_batch_size"], (
        f"`build_eval_pipeline` must be handed `config.selfplay.leaf_batch_size` — the SAME "
        f"key self-play resolves — so deploy and self-play cannot fork. Found: {sources!r}. "
        f"A literal or a second key here re-opens the train/deploy mismatch R318 closed."
    )
