"""The deploy head searches at the config's OWN `selfplay.leaf_batch_size`.

THE DEFECT, measured: `select_move` called `select_leaves(1)` — hardcoded — so a 128-sim move
issued 128 BLOCKING single-board GPU round-trips. Three SIGUSR1 stack samples of a live eval
child landed in the identical frame while the card sat at 5%: overhead-bound, not compute-bound.
A 32-game gate block is ~130 000 such round-trips, 22-44 minutes with the GPU idle, which
reproduces the observed `games_total: 0` at the round timeout. The fix is an ALIGNMENT — the
net's targets are generated by `k=8` leaf-batched self-play search, so a deploy head at `k=1`
was an unexamined train/deploy mismatch. The NODE BUDGET must stay `n_sims` for every `k`, or a
faster search would simply be a weaker one.
"""
from __future__ import annotations

import ast
from pathlib import Path

import pytest

from mantis._engine import Board
from mantis.arena.deploy_head import DeployHeadPlayer

_REPO = Path(__file__).resolve().parents[2]
_ENCODING = "gnn_axis_v1"
_POLICY_LEN = 362


def _counting_expand_fn(calls: list[int]):
    """An expand collaborator that RECORDS the batch width it was handed, per call."""
    def _expand(tree, leaves) -> None:
        calls.append(len(leaves))
        tree.expand_and_backup(
            [[0.0] * _POLICY_LEN for _ in leaves], [0.0] * len(leaves)
        )
    return _expand


def _counting_infer_fn(calls: list[int]):
    """The grid arm's per-leaf collaborator; one entry per LEAF, comparable to the round-trips."""
    def _infer(_board):
        calls.append(1)
        return [0.0] * _POLICY_LEN, 0.0
    return _infer


def _play_one_move(*, n_sims: int, leaf_batch_size: int) -> list[int]:
    """One `select_move` on the GRAPH arm; returns the per-call batch widths."""
    calls: list[int] = []
    player = DeployHeadPlayer(
        expand_fn=_counting_expand_fn(calls), n_sims=n_sims, leaf_batch_size=leaf_batch_size, c_visit=50.0, c_scale=1.0, search_kind="puct", gumbel_m=16, gumbel_seed=0,
    )
    player.new_game()
    player.select_move(Board.with_encoding_name(_ENCODING))
    return calls


# the mechanism: round-trips fall, node budget does not
@pytest.mark.parametrize("k", [1, 2, 4, 8, 16, 128])
def test_the_node_budget_is_EXACTLY_n_sims_at_every_batch_width(k: int) -> None:
    """FIXED NODES: without it the fix is indistinguishable from searching LESS, and a
    throughput knob would move deploy STRENGTH. `select_leaves(k)` returns fewer than `k` on a
    cold tree (measured 1, 1, then k), so a budget credited by the REQUEST spends ~11% fewer
    nodes at k=8 than at k=1 — the budget must advance by leaves returned, exactly."""
    n_sims = 128
    calls = _play_one_move(n_sims=n_sims, leaf_batch_size=k)
    assert sum(calls) == n_sims, (
        f"leaf_batch_size={k} evaluated {sum(calls)} leaves against a budget of exactly "
        f"{n_sims} (widths {calls}). Batching changes how the budget is SPENT, never how much "
        f"of it is — otherwise the batch width is a hidden strength dial."
    )
    assert all(w <= k for w in calls), (
        f"no single request may exceed the batch width: widths {calls} at k={k}"
    )


def test_batching_COLLAPSES_the_round_trip_count_which_is_the_whole_fix() -> None:
    """THE MECHANISM, pinned as a COUNT rather than a duration, and compared against k=1 because
    the exact count depends on the tree's cold-start ramp (1, 1, then k)."""
    n_sims = 128
    at_1 = _play_one_move(n_sims=n_sims, leaf_batch_size=1)
    at_8 = _play_one_move(n_sims=n_sims, leaf_batch_size=8)

    assert len(at_1) == n_sims, f"k=1 must issue one round-trip per sim; got {len(at_1)}"
    assert sum(at_1) == sum(at_8) == n_sims, "both must spend the identical node budget"
    assert len(at_8) * 4 < len(at_1), (
        f"k=8 issued {len(at_8)} blocking round-trips against k=1's {len(at_1)} for the SAME "
        f"{n_sims} nodes. This collapse IS the fix: at k=1 a 128-sim move made 128 blocking "
        f"GPU round-trips, ~130k per gate block, which is the measured cause of "
        f"RECAL-SITTING-3's games_total: 0 inside a 3600 s budget."
    )


def test_a_short_final_batch_never_OVERSPENDS_the_budget() -> None:
    """The remainder case: `min(k, remaining)` clamps the last request, or a move overspends."""
    calls = _play_one_move(n_sims=10, leaf_batch_size=4)
    assert sum(calls) == 10, f"10 nodes requested, {sum(calls)} evaluated (widths {calls})"


def test_k_equals_one_is_byte_for_byte_the_old_loop() -> None:
    """k=1 still requests one leaf per call, `n_sims` times — the pre-existing oracles' shape."""
    calls = _play_one_move(n_sims=7, leaf_batch_size=1)
    assert calls == [1] * 7, f"k=1 must request one leaf per call, 7 times; got {calls}"


def test_the_grid_arm_batches_too_and_is_not_left_behind() -> None:
    """The grid arm batches too — asserted separately because it reaches the net through a
    PER-LEAF `infer_fn`, so a one-arm fix would pass every graph-arm row."""
    calls: list[int] = []
    player = DeployHeadPlayer(
        infer_fn=_counting_infer_fn(calls), n_sims=12, leaf_batch_size=4, c_visit=50.0, c_scale=1.0, search_kind="puct", gumbel_m=16, gumbel_seed=0,
    )
    player.new_game()
    player.select_move(Board.with_encoding_name(_ENCODING))
    assert sum(calls) == 12, (
        f"the grid arm must still evaluate every one of the 12 budgeted leaves; got {sum(calls)}. "
        f"The per-leaf infer_fn count is the node budget on this arm, and it is the same 12 the "
        f"graph arm spends — the arms differ in transport, never in how much they search."
    )


# the knob: required, validated, and SHARED with self-play
@pytest.mark.parametrize("bad", [0, -1])
def test_a_batch_width_below_one_is_REFUSED_not_clamped(bad: int) -> None:
    """A silent clamp to 1 would restore the exact defect this row exists to close."""
    with pytest.raises(ValueError, match="leaf_batch_size"):
        DeployHeadPlayer(infer_fn=_counting_infer_fn([]), n_sims=4, leaf_batch_size=bad, c_visit=50.0, c_scale=1.0, search_kind="puct", gumbel_m=16, gumbel_seed=0)


def test_leaf_batch_size_has_NO_DEFAULT_and_must_be_stated() -> None:
    """A default here would be a search regime nobody minted: omitting it is a TypeError."""
    with pytest.raises(TypeError, match="leaf_batch_size"):
        DeployHeadPlayer(infer_fn=_counting_infer_fn([]), n_sims=4, c_visit=50.0, c_scale=1.0, search_kind="puct", gumbel_m=16, gumbel_seed=0)  # type: ignore[call-arg]


def test_deploy_and_selfplay_read_THE_SAME_CONFIG_KEY() -> None:
    """Deploy and self-play must read THE SAME config key, checked structurally: the root hands
    `build_eval_pipeline` the very attribute the self-play hparams resolver reads, so a literal
    or a second key here would leave both regimes green while forking them."""
    tree = ast.parse((_REPO / "src" / "mantis" / "run.py").read_text(encoding="utf-8"))
    sources = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        func = node.func
        name = func.id if isinstance(func, ast.Name) else getattr(func, "attr", None)
        if name != "build_eval_pipeline":
            continue
        for kw in node.keywords:
            if kw.arg == "leaf_batch_size":
                sources.append(ast.unparse(kw.value))

    assert sources == ["config.selfplay.leaf_batch_size"], (
        f"`build_eval_pipeline` must be handed `config.selfplay.leaf_batch_size` — the SAME "
        f"key self-play resolves — so deploy and self-play cannot fork. Found: {sources!r}. "
        f"A literal or a second key here re-opens the train/deploy mismatch R318 closed."
    )
