"""Dev-only deterministic opening-book minter (design §a.2).

CLI: uv run python tools/mint_opening_book.py --seed S --plies P --n N --out PATH.json

Openings are generated by uniform-random selection over `board.legal_moves()` for the
first `plies` plies from an empty board (the SAME mechanics run3's on-the-fly gate-opening
generator used, deploy_strength_eval.py:302,308-311) — driven by a single seeded
`random.Random(seed)` stream consumed in generation order, so regenerating with identical
args reproduces byte-identical output (test-pinned:
tests/arena/test_books.py::test_book_v1_reproducible_from_minter_args).
"""
from __future__ import annotations

import argparse
import json
import random
import sys
from pathlib import Path

from mantis._engine import Board

#: The board encoding minted openings are generated (and later legality-replayed) against.
_MINT_ENCODING = "gnn_axis_v1"


def _mint_one_opening(*, plies: int, rng: random.Random) -> list[list[int]]:
    board = Board.with_encoding_name(_MINT_ENCODING)
    moves: list[list[int]] = []
    for _ in range(plies):
        legal = board.legal_moves()
        if not legal:
            break
        q, r = rng.choice(legal)
        board.apply_move(q, r)
        moves.append([q, r])
    return moves


def mint_book(*, seed: int, plies: int, n: int) -> dict:
    """Deterministic book payload: `{"openings": [{"id": i, "moves": [...]}]}`."""
    rng = random.Random(seed)
    openings = [
        {"id": i, "moves": _mint_one_opening(plies=plies, rng=rng)} for i in range(n)
    ]
    return {"openings": openings}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--seed", type=int, required=True)
    parser.add_argument("--plies", type=int, required=True)
    parser.add_argument("--n", type=int, required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args(argv)

    payload = mint_book(seed=args.seed, plies=args.plies, n=args.n)
    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(payload, sort_keys=True, separators=(",", ":")), encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
